### ISSUE TITLE
Dart compatibilization

### ISSUE THREAD

**Issue by ovidals** [pak3nuh/dart_pact_consumer#11]
Hi,

I would like to use this library on a flutter application that is using dart 2.15. Is there any option to compatibilize it?

Thank you!

**Comment by pak3nuh** [comment]
Hey,

Its possible to overcome null safety with an adaption layer, but FFI made breaking changes in dart 2.12. The only way is to bump the dart version.

**Comment by pak3nuh** [comment]
Closing
