### ISSUE TITLE
New release on pub.dev

### ISSUE THREAD

**Issue by gtudan** [pak3nuh/dart_pact_consumer#8]
We've successfully tested the recent version with the Junit-PACT Consumer Tests against a broker and they work great. Could you please do a release on pub.dev, so that we don't have to reference the master in our pub spec anymore?

Thanks you!

**Comment by pak3nuh** [comment]
Hi @gtudan 
Just published what is on master

**Comment by gtudan** [comment]
Cool, thanks a lot
